name: CI Create Release

on:
  push:
    tags:
      - 'v*'

jobs:

  server-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'
          cache: true

      - name: Build for Windows
        run: GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o goprocess.exe .

      - name: Build for Linux
        run: GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o goprocess .

      # - name: Build
      #   run: |
      #     python release.py

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          # token: ${{secrets.TOKEN}}
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref_name }}
#          body_path: ./build/changelog.md
          draft: false
          prerelease: false
          files: |
            goprocess.exe
            goprocess